### ISSUE TITLE
Not seeing in game 

### ISSUE THREAD

**Issue by sliceandice** [Mokulu/Drakewatcher-Manuscripts#1]
Addon is loading up just not seeing it in game. I do use bazooka bar addon and not showing up to show or hide it so im guessing that the addon is not compatable with bar addons?

**Comment by Mokulu** [comment]
The addon utilizes the new Addon Compartment and can be found in there:
![image](https://github.com/Mokulu/Drakewatcher-Manuscripts/assets/19164690/31d5a1af-8d1d-45d4-bea9-eb8894bd1e00)

Additonally, the window can be opened using the command `/dwms`.

**Comment by sliceandice** [comment]
I use sexy map. disabled it and still no addon compartment button showing up. Not a big deal as all I care about is if i know the manuscript or not as it showes if you have learned it or not :) Thanks for the addon
